name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Setup GCC
      uses: egor-tensin/setup-gcc@v1.3

    - name: Run
      run: make

    - name: Upload build result
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ./*
